### ISSUE TITLE
Printing response information in different formats

### ISSUE THREAD

**Issue by schallert** [bryanl/doit#1]
Hey, I've been playing with the docli tool recently and have enjoyed using it. One thing that I think could make it easier to use would be if some of the output was a bit more human-friendly to read and displayed the most important information. Although the json output is very informational and provides everything you need to know, usually when I'm listing my droplets I'm more concerned with basic info such as its IP address as opposed to what regions its base image is available in.

To that end, I've been trying out using the functionality of the awesome [text/tabwriter](http://golang.org/pkg/text/tabwriter/) package recently to add the option to have a tabular output format for some commands. For example:

```
$ ./docli droplet list --tabular
ID       Name           IP Address      Memory  VCPUs  Disk  Region  Image             Status
xxxxxx   xxxxxxxx-SF    xxx.xxx.xxx.xxx 1024    1      30    sfo1    ubuntu-14-10-x64  active
xxxxxxx  xxxxxxxxx-nyc  xxx.xxx.xxx.xxx 1024    1      30    nyc3    ubuntu-14-10-x64  active
```

Would this type of functionality be something the project would be interested in incorporating? I'd be happy to keep working on it!

**Comment by bryanl** [comment]
I've been thinking about how to handle this. Perhaps there should be three potential output formats: JSON, YAML, and text.  If you don't mind, I will take a pass at adding text output for all the applicable commands.

**Comment by bryanl** [comment]
@schallert I haven't forgotten about this yet. I'll commit something in the next day or so that will produce a more human readable output. Using jq to parse is fun, but more mental energy that I want to expend most time.

**Comment by bryanl** [comment]
@schallert I've introduced text output for almost everything. I'll finish up the rest before the next point release.

**Comment by schallert** [comment]
@bryanl this is awesome, glad to see the new feature!
