### ISSUE TITLE
Droplet creation seems to hang indefinitely

### ISSUE THREAD

**Issue by brennen** [bryanl/doit#51]
Testing like so:

```
$ doit version
0.7.0-dev
$ doit droplet create test --size 1gb --image debian-8-x64 --region nyc1 --enable-backups --verbose
```

A variation without `--enable-backups` also hangs.  All other operations I've tested so far, including `droplet delete`, seem to work, so I'm assuming valid credentials.

**Comment by brennen** [comment]
As an additional bit of detail, short options for `droplet create` all seem to fail with some variation on the following:

```
$ doit droplet create test -s 1gb -i debian-8-x64 -r nyc1      
Error: unknown shorthand flag: 's' in -s
Usage:
  doit droplet create NAME [NAME ...] [flags]
...
```

I was going to file this as a separate issue, but possibly it's related?

**Comment by bryanl** [comment]
@brennen Thanks for reporting. I'll dig in and see if I can reproduce it.

**Comment by nickvanw** [comment]
hey @brennen - I ran into this today and I think I've nailed the bug down! I'll have a PR in a moment with a fix.

**Comment by brennen** [comment]
Thanks @nickvanw!
